schema_version = "0.1.0"
id = "SHIRAKUMO_rectangle_tools"
name = "Rectangle Tools"
version = "0.0.1"
tagline = "Tools to more easily draw rectangles in edit mode"
maintainer = "Yukari Hafner"
type = "add-on"
permissions = []
tags = []
blender_version_min = "4.2.0"
license = ["SPDX:zlib"]
website = "https://github.com/Shirakumo/blender-addons/"
copyright = ["Yukari Hafner"]
