schema_version = "0.1.0"
id = "SHIRAKUMO_sf3_io"
name = "Shirakumo SF3 IO"
version = "0.0.1"
tagline = "Export/Import support for Simple File Format Family (SF3) files."
maintainer = "Yukari Hafner"
type = "add-on"
permissions = ["files"]
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:zlib"]
website = "https://github.com/Shirakumo/blender-addons/"
copyright = ["Yukari Hafner"]
