schema_version = "1.0.0"
id = "SHIRAKUMO_trial_extensions"
name = "Shirakumo Trial Extensions"
version = "0.0.1"
tagline = "Editor extensions for extra features supported by the Trial game engine."
maintainer = "Yukari Hafner"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later","SPDX:Zlib"]
website = "https://shirakumo.org/project/blender-addons/"
copyright = ["Yukari Hafner"]

[permissions]
files = "Import/export SF3 from/to disk"

