name: Build Release
on: [create, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          path: trial
      - name: Checkout gltf physics
        uses: actions/checkout@v4
        with:
          repository: shirakumo/glTF_Physics_Blender_Exporter
          path: gltf_physics
      - name: Checkout gltf io
        uses: actions/checkout@v4
        with:
          repository: KhronosGroup/glTF-Blender-IO
          path: gltf_io
          branch: KHR_animation_pointer
      - name: Build ZIP files
        run: |
          cd $GITHUB_WORKSPACE/trial/addons/
          cp ../LICENSE */
          zip -r $GITHUB_WORKSPACE/SHIRAKUMO_trial_extensions.zip .
          cd $GITHUB_WORKSPACE/gltf_physics/addons/
          cp ../LICENSE.txt */
          zip -r $GITHUB_WORKSPACE/KHR_physics_rigid_bodies.zip .
          cd $GITHUB_WORKSPACE/gltf_io/addons/
          cp ../LICENSE.txt */
          zip -r $GITHUB_WORKSPACE/KHR_gltf_io.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trial-blender-addons
          path: |
            SHIRAKUMO_trial_extensions.zip
            KHR_physics_rigid_bodies.zip
            KHR_gltf_io.zip
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        continue-on-error: true
        with:
          allowUpdates: true
          name: Release ${{ github.ref_name }}
          artifacts: |
            SHIRAKUMO_trial_extensions.zip
            KHR_physics_rigid_bodies.zip
            KHR_gltf_io.zip
